language: node_js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++-4.9-dev
notifications:
  email: false
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
before_script:
- npm ls --production >/dev/null
- npm run greenkeeper:update-lockfile
after_script: npm run greenkeeper:upload-lockfile
after_success: npm run coverage:report
deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
  - GK_LOCK_COMMIT_AMEND=true
  - secure: E+dDmZZpJeudln5DLihL7l1HX9BDfDJlOPgkP54fdhth56cPEUxrtRMJePU8XGgTU6p2VgTF3+AvojzgLluLek5Wv7sbT/+OavUmWrhq1dFAffTJk/KIFDbSvltdxJe8A+X8N1m9rcE7gFKJgq1IJ0KSGVe0cNsagmVlZ0sLuPmk/O+DPFQiZlYsAIuJuzZV4PpYXyhcROAZyf2hZ3gsI/Ti9Qsf7LYEKPUAkDoCEf3QmtvTXA0dHi0HRTBeJqlngLj6na+U9qL+lFxBFbeWuSvxaiVrJ0Oqfq/6MKZ1XBS3rp6/LObIPFX84UWN3D9bZ/AVLKZQyCz75Yg5B+gv6lFdSMWw4Z6qc1TDsa4jT3soZ0w4OCdNVAz208Jut7OLa/CuInqPcJ7cHrRDnBpzFan+TNAvmx96jQ7jhiJJI5E7oYcTl0BHlY1gGpSEjxjKIV7vA42gTjKnIgpki5n5C7dvKTR9UfxEAzkFJRRNKddC8QuCCeQ0NUB1CxMt/7r8DzWTqXUyAZPiWQJfB4hSZTRvvS5RmJuxG9zdw1TQeW/PV53zXHgQZlIxt5vQ6Mxdn9HU78K6ji0Hb8FEgyGIkFr2WoYEh26JYcxgJJ8r3KoUCTqVyHOjaj5v3DiUe2icXoECAPyag5KfPqqyX3Tukz30iQLnFWCZCMqOuGbpcB0=
  - secure: tNSxUrVUM4/o4EE/2d2ZFkEeK1HWzNHK5mRxorm6jquC6vj1JsH0hQQ77t5s4w8/Z2vTcFT1/dZLLFGmRfMAztWFN9r+26ezqXIbzf2G4nehoMtQERAo9zUcAn00dM2Z/f65uaIApI30He6OtATG1rV/O3w4gOx/AExPvl6qYEinet1rpn4991oyqr8qexZzOl2ycZ53BehV3nmmFz408V1ZfMLoBJxRe5xBLM1Hye9N1k6CpDs/K7CXfM6BRVw+dG0/9jeDrmGjPKtO9w6oAMbwtRcvsBgUW1JOUqxptLcP/ma6dROmU6pCxHL3yoRW7GvBtLmwufMQpRydpjPlPY617+ZsQgKXKgFdrqblvCYEBpusTGry4+66ncDtNtfNQrAhqDJPE2xUaU1bCpm9ntCPbHISRC8ZGbqX4Lk/Ll+QGkoV98tS0AmOWFBcVrOxqad4UKmbhs+yssx7bqiP0viMn84XtdREXpi6oogKjBd6kbmUCIEUBuIs4jyM24f4Clole9FESiTCf/IYhFoFXzOm1C+Wa4G60//B90rMP/Wv6V6HoYt6SYRn/3OpdCxfbyFUhXRvBoQKX7xHMvUMy8zMk1TXoD6/cyreliWcMkNJHWk+FCqCuPiCe4wxtiKbyNDNaAttoEeZoJgBAZCvRpX1K2neWY+/JmfTnGVDFK8=
