language: node_js
notifications:
  email: false
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
before_script:
- npm ls >/dev/null
- npm run greenkeeper:update-lockfile
after_script: npm run greenkeeper:upload-lockfile
